dist: bionic
sudo: false

language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

  - os: osx
    compiler: clang
    env:
      - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - ./ci/install-${TRAVIS_OS_NAME}.sh

script: ./ci/travis.sh

addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0
    packages:
    - g++-7
    - clang-5.0
    - gcovr
    - locv

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

notifications:
  email: false
