version: 2

jobs:
    build:
        docker:
            - image: "debain:stretch"
        setps:
            - checkout
            - run:
                name: Installing SUDO
                command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
            - run:
                name: Installing gcc
                command: 'apt-get update && apt-get install -y gcc g++'
            - run:
                name: Install Dependencies
                command: ./ci/install-linux.sh
            - run:
                name: Build & Test
                command: ./ci/travis.sh
