version: 2.0
jobs:
  build:
    docker:
       - image: "ubuntu:latest"
    steps:
        - run:
            name: Installing SUDO
            command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
        - run:
            name: Installing gcc
            command: 'apt-get update && apt-get install -y gcc g++ python-pip wget git'
        - checkout
        - run:
            name: Checkout submodule
            command: 'git submodule init & git submodule update'
        - run:
            name: Install Dependencies
            command: ./ci/install-linux.sh
        - run:
            name: Build & Test
            command: ./ci/travis.sh
